config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :students
  resources :instructors
  resources :courses do
    delete 'terminate' => 'cohorts#destroy'
  end

  resources :cohorts do
    delete 'terminate' => 'cohorts#destroy'
  end

  get 'cohorts/new'
  get 'cohorts/show'
  get 'cohorts/edit'
  get 'cohorts/index'
  get 'courses/new'
  get 'courses/show'
  get 'courses/edit'
  get 'courses/index'
  get '/signup' => 'instructors#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'instructors/show'
  get 'instructors/edit'
  get 'instructors/index'
  get 'students/new'
  get 'students/show'
  get 'students/edit'
  get 'students/index'
  get 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def full_name
    self.first_name+ " " + self.last_name
  end

end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_one :instructor
  has_one :course
  has_many :students
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  before_save { self.email = email.downcase }
  has_secure_password
  validates :password, presence: true, length: {maximum: 32, minimum: 2}
  validates :email, presence: true, length: { maximum: 100 }

  # def User.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MID_COST :
  #                                                 BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end
  # def authenticated?(attribute, token)
  #   digest = send("#{attribute}_digest")
  #   return false if digest.nil?
  #   BCrypt::Password.new(digest).is_password?(token)
  # end
end

app/models/student.rb
class Student < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user


  def current_user
    @current_user ||= Instructor.find(session[:user_id]) if session[:user_id]
  end
  def require_user
    redirect_to '/' unless current_user
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :require_user , except: [:destroy]

  def new
    @instructors = Instructor.all
    @students = Student.all
    @courses = Course.all
    @cohort = Cohort.new
  end

  def create
    @instructors = Instructor.all
    @students = Student.all
    @courses = Course.all
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      redirect_to cohorts_path
    else
      render 'new'
    end
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def edit
    @instructors = Instructor.all
    @students = Student.all
    @courses = Course.all
    @cohort = Cohort.find(params[:id])
  end

  def update
    @instructors = Instructor.all
    @students = Student.all
    @courses = Course.all
    @cohort = Cohort.find(params[:id])
    if @cohort.update(cohort_params)
      redirect_to cohorts_path
    else
      render 'edit'
    end

  end

  def index
    @cohorts = Cohort.all
  end


  def destroy
    @cohort = Cohort.find(params[:id])
    p "Terminating #{@cohort.name}"
    @cohort.destroy
    respond_to do |format|
      format.js
      format.html { p 'html response'; redirect_to cohorts_path }
    end
  end


  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :course_id, :student_id, :instructor_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_user, except: [:destroy]
  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to courses_path
    else
      render 'edit'
    end

  end

  def index
    @courses = Course.all
  end

  def destroy
    @course = Course.find(params[:id])
    p "Terminating #{@course.name}"
    @course.destroy
    respond_to do |format|
      format.js
      format.html { p 'html response'; redirect_to cohorts_path }
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :total_hours)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :require_user , except: [:new, :create]
  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      session[:user_id] = @instructor.id
      redirect_to instructors_path
    else
      render 'new'
    end
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update(instructor_params)
      redirect_to instructors_path
    else
      render 'edit'
    end
  end

  def index
    @instructors = Instructor.all
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    p "Terminating #{@instructor.full_name}"
    @instructor.destroy
    respond_to do |format|
      format.js
      format.html { p 'html response'; redirect_to instructors_path }
    end
  end

  private



  def instructor_params
    params.require(:instructor).permit(:first_name, :last_name, :age, :salary, :education, :email, :password, :admin)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @instructor = Instructor.find_by_email(params[:session][:email])
      if @instructor && @instructor.authenticate(params[:session][:password])
          session[:user_id] = @instructor.id
          redirect_to pages_home_path
      else
        redirect_to '/'
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :require_user , except: [:destroy]
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path
    else
      render 'edit'
    end

  end

  def index
    @students = Student.all
  end

  def destroy
    @student = Student.find(params[:id])
    p "Terminating #{@student.full_name}"
    @student.destroy
    respond_to do |format|
      format.js
      format.html { p 'html response'; redirect_to students_path }
    end
  end


  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :education, :cohort_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
<%= f.label 'Name', :class => "label" %>
<%= f.text_field :name, :class => "form-control"%><br>
<%= f.label 'Start date', :class => "label" %>
<%= f.date_field :start_date, :class => "form-control" %><br>
<%= f.label 'End date', :class => "label" %>
<%= f.date_field :end_date, :class => "form-control" %><br>
<%= f.label 'Course', :class => "label" %>
<%= f.collection_select :course_id, @courses, :id, :name, {include_blank: true} , :class => "form-control" %><br>
<%= f.label 'Instructor', :class => "label"%>
<%= f.collection_select :instructor_id, @instructors, :id, :full_name , {include_blank: true}, :class => "form-control"  %><br>
<%= f.submit :class=>"btn" %>
<% end %>

app/views/cohorts/destroy.js.erb
$('.terminate').bind('ajax:success', function() {
  console.log('deleting ...');
  $(this).closest('div').fadeOut(1000);
});

app/views/cohorts/edit.html.erb
<div class="newCohort">
  <h3>Edit cohort</h3>
  <%= render 'cohorts/form' %>
</div>

app/views/cohorts/index.html.erb
<h1>Cohorts   <button class="btn pageBtn"><%= link_to "New", cohorts_new_path%></button></h1>
<div class="myContainer">
  <% @cohorts.each do |c|%>

    <div class="cohort">

      <h3>
        <%= c.name %>
        <button class="btn infoButton"><%= link_to 'Edit', edit_cohort_path(c)%></button>
        <button class="btn infoButton"><%= link_to 'Delete', cohort_path(c.id), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'terminate' %></button>
      </h3>

      <div class="cohortInfo">

        <p>Starts: <%= c.start_date%></p>
        <p>Ends: <%= c.end_date  %></p>
        <% Course.where(id: c.course_id).each do |x| %>
          <p>Course: <%= x.name%></p>
        <% end %>
        <% Instructor.where(id: c.instructor_id).each do |i|%>
          <p>Instructor: <%= i.full_name%></p>
        <% end %>
        <button class="showStudents btn">Students</button>
        <div class="studentList">
          <h5>Name:</h5>
          <% Student.where(cohort_id: c.id).each do |s|%>
          <p><%= s.full_name %></p>
          <% end %>

        </div>
      </div>
    </div>

  <%end%>

</div>

app/views/cohorts/new.html.erb
<div class="newCohort">
  <h3>New cohort</h3>
  <%= render 'cohorts/form'%>
</div>

app/views/cohorts/show.html.erb
<h1><%= current_user.full_name%></h1>
<div class="mycohort">
<h3><%= @cohort.name %></h3>
<p>Starts: <%= @cohort.start_date.strftime("%B %d, %Y") %></p>
<p>Ends: <%= @cohort.end_date.strftime("%B %d, %Y") %></p>
<% Course.where(id: @cohort.course_id).each do |c|%>
  <p>Course: <%= c.name%></p>
<% end %>
<%if !current_user%>
<% Instructor.where(id: @cohort.instructor_id).each do |i|%>
  <p>Instructor: <%= i.full_name %></p>
<% end %>
<% end %>
<h5>Students</h5>
  <% Student.where(cohort_id: @cohort.id).each do |s|%>
    <p><%= s.full_name %> <span><%= link_to 'Show', s %> <%= link_to 'Edit', edit_student_path(s)%></span></p>
  <% end %>
</div>

app/views/courses/_form.html.erb
<%= form_for@course do |f|%>
<%= f.label 'Name', :class => 'label'%>
<%= f.text_field :name, :class => "form-control"%><br>
<%= f.label 'Hours', :class => 'label'%>
<%= f.number_field :total_hours, :class => "form-control"%><br>
<%= f.submit :class=>"btn" %>
<%end%>

app/views/courses/destroy.js.erb
$('.terminate').bind('ajax:success', function() {
  console.log('deleting ...');
  $(this).closest('div').fadeOut(1000);
});

app/views/courses/edit.html.erb
<div class="newCourse">
  <h3>Edit Course</h3>
  <%= render 'courses/form'%>
</div>

app/views/courses/index.html.erb
<h1>Courses <button class="btn pageBtn"><%= link_to "New", courses_new_path %></button></h1>
<div class="wrapper">
  <% @courses.reverse.each do |c| %>
  <div class="course grid-item">
    <h3><%= c.name %> <button class="btn infoButton"><%= link_to 'Edit', edit_course_path(c)%></button>
      <button class="btn infoButton"><%= link_to 'Delete', course_path(c.id), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'terminate' %></button></h3>
    <div class="courseInfo">
      <h4>Total hours: <%= c.total_hours %></h4>
    </div>
  </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="newCourse">
  <h3>New Course</h3>
  <%= render 'courses/form'%>
</div>

app/views/courses/show.html.erb
<h3>Course name: <%= @course.name %></h3>
<h4>Total hours: <%= @course.total_hours%></h4>

app/views/instructors/_form.html.erb
<%= form_for @instructor do |f| %>
<%= f.label 'First name', :class => 'label'%>
<%= f.text_field :first_name, :class => "form-control" %><br>
<%= f.label 'Last name', :class => 'label'%>
<%= f.text_field :last_name,:class => "form-control" %><br>
<%= f.label 'Age', :class => 'label'%>
<%= f.number_field :age,:class => "form-control"%><br>
<%= f.label 'Education', :class => 'label'%>
<%= f.text_field :education, :class => "form-control"%><br>
<%= f.label 'Salary', :class => 'label'%>
<%= f.number_field :salary, :class => "form-control" %><br>
<%= f.label 'Email', :class => 'label'%>
<%= f.email_field :email, :class => "form-control"%><br>
<%= f.label 'Password', :class => 'label'%>
<%= f.password_field :password, :class => "form-control"%><br>
<%= f.submit :class=>"btn" %>
<% end %>

app/views/instructors/destroy.js.erb
$('.terminate').bind('ajax:success', function() {
  console.log('deleting ...');
  $(this).closest('div').fadeOut(1000);
});

app/views/instructors/edit.html.erb
<div class="newInstruc">
  <h3>Edit Instructor</h3>
  <%= render 'instructors/form'%>
</div>

app/views/instructors/index.html.erb
<h1>Instructors <button class="btn pageBtn"><%= link_to "New", new_instructor_path %></button></h1>
<div class="myContainer">
  <% @instructors.reverse.each do |i| %>
    <div class="instructor">
      <h3><%= i.full_name.capitalize %> <button class="btn infoButton"><%= link_to 'Edit', edit_instructor_path(i)%></button>
        <button class="btn infoButton"><%= link_to 'Delete', instructor_path(i.id), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'terminate' %></button>
      </h3>
      <div class="instructorInfo">
        <p>Age: <%= i.age %></p>
        <p>Education: <%= i.education %></p>
        <p>Salary: $<%= i.salary %></p>
        <p>Email: <%= i.email %></p>
        <button class="showCohots btn">Cohorts</button>
        <div class="cohortList">
          <%Cohort.where(instructor_id: i.id).each do |c|%>
            <p><%=c.name%>
            <button class="btn infoButton cohortBtn"><%= link_to 'Show', c %></button></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/instructors/new.html.erb
<div class="newInstruc">
  <h3>New Instructor</h3>
  <%= render 'instructors/form'%>
</div>

app/views/instructors/show.html.erb
<h3><%= @instructor.first_name.capitalize %> <%= @instructor.last_name.capitalize %></h3>
<p>Age: <%= @instructor.age %></p>
<p>Education: <%= @instructor.education%></p>
<p>Salary: $<%= @instructor.salary%></p>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Panel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="main">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">Dev Academia</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if current_user %>
            <li class="nav-item active">
              <a class="nav-link" href="/pages/home">Home
                <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">

              <%= link_to "Log out", logout_path, method: "delete", :class =>"nav-link" %>
            </li>
            <!-- <elsif !current_user %>
            <li class="nav-item">
              <a class="nav-link" href="/">Log in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Sign up</a>
            </li> -->
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div class="logo">
      <img src="/logo_transparent2.png" alt="">

    </div>
    <%if current_user%>
    <div class="secondary-nav">
      <ul class="nav nav-tabs" >
        <li class="nav-item sub">
          <a class="nav-link" href="/cohorts">Cohorts</a>
        </li>
        <li class="nav-item sub">
          <a class="nav-link" href="/students">Students</a>
        </li>
        <li class="nav-item sub">
          <a class="nav-link" href="/instructors">Instructors</a>
        </li>
        <li class="nav-item sub">
          <a class="nav-link" href="/courses">Courses</a>
        </li>
      </ul>
    </div>
    <%end%>
    <%= yield %>


  </body>
</html>

app/views/pages/home.html.erb
<h1>Dashboard</h1>
<div class="home">
  <div class="welcome">
    <h2>Welcome <%= current_user.full_name.capitalize %></h2>
    <h3>Your Cohorts</h3>
    <%Cohort.where(instructor_id: current_user.id).each do |c|%>
        <p><%=c.name%>
        <button class="btn infoButton cohortBtn"><%= link_to 'Show', c %></button></p>
    <% end %>
  </div>

</div>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
<%= f.label 'First name', :class => 'label'%>
<%= f.text_field :first_name, :class => "form-control"%><br>
<%= f.label 'Last name', :class => 'label'%>
<%= f.text_field :last_name,:class => "form-control" %><br>
<%= f.label 'Age', :class => 'label'%>
<%= f.number_field :age,:class => "form-control"%><br>
<%= f.label 'Education', :class => 'label'%>
<%= f.text_field :education,:class => "form-control"%><br>
<%= f.label 'Pick a cohort', :class => "label" %>
<%= f.collection_select :cohort_id, Cohort.all , :id, :name, {include_blank: true}, :class => "form-control" %><br>
<%= f.submit :class=> "btn" %>
<% end %>

app/views/students/destroy.js.erb
$('.terminate').bind('ajax:success', function() {
  console.log('deleting ...');
  $(this).closest('div').fadeOut(1000);
});

app/views/students/edit.html.erb
<div class="newStudent">
  <h3>Edit student</h3>
  <%= render 'students/form'%>
</div>

app/views/students/index.html.erb
<h1>Students <button class="btn pageBtn"><%= link_to "New", students_new_path %></button></h1>
<div class="grid-container">
  <% @students.reverse.each do |s| %>
    <div class="grid-item">
      <h6><%= s.full_name.capitalize %> <button class="btn infoButton"><%= link_to 'Edit', edit_student_path(s)%></button>
        <button class="btn infoButton"><%= link_to 'Delete', student_path(s.id), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'terminate' %></button>

    </h6>
      <div class="studentInfo">
        <p>Age: <%= s.age %></p>
        <p>Education: <%= s.education %></p>
        <% Cohort.where(id: s.cohort_id).each do |c|%>
          <p class="enrolled">Enrolled in <%= c.name %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<div class="newStudent">
  <h3>New student</h3>
  <%= render 'students/form'%>
</div>

app/views/students/show.html.erb
<h1><%= @student.first_name.capitalize%> <%= @student.last_name.capitalize%></h1>
<p>Age: <%= @student.age %></p>
<p>Education: <%= @student.education%></p>